apiVersion: v1
kind: Service
metadata:
  name: activemq
  namespace: queue
spec:
  selector:
    app: activemq
  type: NodePort
  ports:
    - name: broker
      port: 61616
      targetPort: 61616
      nodePort: 31616

    - name: webconsole
      port: 8161
      targetPort: 8161
      nodePort: 31861